server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册金Eureka服务器的服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WpyPengyue/springcloud-config.git
          ##抖索目录
          search-paths:
            - springcloud-config
      ### 读取分支
      label: master
#rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
# rabbitmq相关配置，暴漏bus刷新配置的端点